services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-app/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: back-app
    build: ./back-app
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-app/.env

  web:
    container_name: my-app
    build: ./my-app
    ports: 
      - 3000:3000
    env_file:
      - my-app/.env.local
    volumes:
      - next-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - next-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - web

volumes:
  postgres-volume:
  next-volume:
