services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-app/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: back-app
    build: ./back-app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-app/.env
    volumes:
      - back-volume:/src/usr/mc-caminhoes

  web:
    container_name: my-app
    build: ./my-app
    ports: 
      - 3000:3000
    env_file:
      - my-app/.env.production
    depends_on:
      - node
    volumes:
      - next-volume:/src/usr/mc-caminhoes


volumes:
  postgres-volume:
  next-volume:
  back-volume:
