name: Build and Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          directory: back-app
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_NEXT_PUBLIC_REACT_BACK: ${{secrets.NEXT_PUBLIC_REACT_BACK}}
          directory: my-app
          file_name: .env.local
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose down && docker compose up -d
